version: '3'

services:
  baram-fe:
    container_name: baram-fe
    build:
      context: ./client
      dockerfile: ./docker/dev.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
  baram-be:
    container_name: baram-be
    build:
      context: ./server
      dockerfile: ./docker/dev.Dockerfile
    restart: always
    ports:
      - 4000:4000
